#!/usr/bin/env bash
# this script installs a nginx server that listens on
# port 80 and retuens a page that contains hello world string

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
