#!/usr/bin/env bash
# This installs Nginx with the following configurations

apt-get update
apt-get install -y nginx

mkdir -p /var/www/html
touch /var/www/html/index.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
