#!/usr/bin/env bash
# This configures HAproxy on our server
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 261762-web-01 34.207.188.42:80 check\n\tserver 261762-web-02 54.237.31.63:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart