#!/usr/bin/env bash
#script that displays infinity and beyond and i am invincible when receiving a sigterm
trap 'echo "I am invincible!!!"' SIGTERM
while :
do
        echo "To infinity and beyond"
        sleep 2
done
