#!/usr/bin/env bash
#script that prints best school using while anf if loop
x=1
while [ $x -le 10 ]
do
        echo "Best School"
        if [ $x -eq 9 ]
        then
            echo "Hi"
        fi
        ((x++))
done
