#!/usr/bin/env bash
#this script resolves localhost and facebok.com with a new IP address
cp /etc/hosts ~/hosts.new
echo '127.0.0.2    localhost' > ~/hosts.new
echo '8.8.8.8      facebook.com' >> ~/hosts.new
cp -f ~/hosts.new  /etc/hosts
