#!/usr/bin/env bash
# This script runs nginx as nginx user
chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo nginx -c "service nginx restart"
